apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
# stringData:
#   DATABASE_PASSWORD:
#   ALIYUN_ACCESS_KEY_ID:
#   ALIYUN_ACCESS_KEY_SECRET:
#   ALIYUN_OSS_STS_ROLE_ARN:
#   WEBAUTHN_RP_ID:
#   WEBAUTHN_ORIGIN:
#   WEBAUTHN_RP_NAME:
