/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Agreement: typeof import('./src/components/Common/Agreement.vue')['default']
    BlogToolBar: typeof import('./src/components/Blog/BlogToolBar.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    Footer: typeof import('./src/components/Common/Footer.vue')['default']
    Header: typeof import('./src/components/Common/Header.vue')['default']
    RotationVerification: typeof import('./src/components/Common/RotationVerification.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
